version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      target: development
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    container_name: rehic-backend-server
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app
      - /app/node_modules
    entrypoint: ["./entrypoint.sh"]
  db:
    container_name: rehicdb
    image: postgres:alpine3.19
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: {}
